spring.application.name=demo

#spring.datasource.url=jdbc:postgresql://localhost:1412/learning
#spring.datasource.username=postgres
#spring.datasource.password=02011214
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# 1. URL - faqat hostname, port va database nomi bo'lishi kerak
# Login va parolni URL ichiga yozish shart emas, pastdagilar yetarli
spring.datasource.url=jdbc:postgresql://dpg-d7aektnkijhs73aki1ng-a.oregon-postgres.render.com:5432/learning_r5yi?sslmode=require

# 2. Foydalanuvchi nomi
spring.datasource.username=learning_r5yi_user

# 3. Parol
spring.datasource.password=ALhfyoDy3ZthUYZfJTIm2nFOKilTbFzk

# Hibernate sozlamalari
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kotlin/Java versiyasiga qarab ba'zan driverni ko'rsatish foydali
spring.datasource.driver-class-name=org.postgresql.Driver